name: graphic
description: A data visualization (charts / chart / charting) library based on Grammar of Graphics.
version: 0.3.0
homepage: https://github.com/entronad/graphic

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
